### ISSUE TITLE
Hned po manuální aktualizaci databáze se neobjeví nové změny

### ISSUE THREAD

**Issue by michaeldojcar** [proscholy/proscholy-phone#11]
Přeposílám Patrikovu reakci z Jira:

Zatím by se měly projevit jen změny v hlavních seznamech, pokud bude přímo otevřená nějaká píseň a ta bude po aktualizaci změněna, tak se změna projeví až po vrácení do seznamu a znovu otevření dané písně.

**Comment by michaeldojcar** [comment]
Přeposílám Patrikovu reakci z Jira:

Zatím by se měly projevit jen změny v hlavních seznamech, pokud bude přímo otevřená nějaká píseň a ta bude po aktualizaci změněna, tak se změna projeví až po vrácení do seznamu a znovu otevření dané písně.

**Comment by michaeldojcar** [comment]
Teď jsem byl v písni, pak jsem ji na API updatovat, refreshl jsem databázi, vyjel na seznam všech písní a pořád mám starý content. Šlo o píseň https://zpevnik.proscholy.cz/pisen/1156/at-jde-mojzis

**Comment by michaeldojcar** [comment]
Teď se mi děje to stejné u písně: https://zpevnik.proscholy.cz/pisen/43/madona
Na API už jsou nové noty, ale v appce po refreshi a restartu pořád staré SVG.

Není to těmi časovými pásmy? :-)

**Comment by Paprikadobi** [comment]
Je to tou změnou, kterou jsem časové pásma upravoval. Od té doby aktualizace nefunguje vůbec i když to z nějakého důvodu vypisuje, že to bylo úspěšné. Upravil jsem to, ale teď se po té manuální aktualizaci rozbije vyhledávání, tak se na to ještě večer podívám.

**Comment by michaeldojcar** [comment]
Otestováno, update už proběhne instantně. :-)
