### ISSUE TITLE
Vlastní Google Play

### ISSUE THREAD

**Issue by michaeldojcar** [proscholy/proscholy-phone#12]
Bylo by pěkné mít vlastní Google Play account, teoreticky by to mohlo i urychlit release a mohli bychom si nachystat Androidí Beta program podobně jako nám běží Apple TestFlight. :-)

**Comment by michaeldojcar** [comment]
Teoreticky bychom mohli založit GPlay účet Glow Space, mohli bychom tak pěkne promovat, že projektu ProScholy se dostává open-source vývoje v rámci komunity Glow Space. Co vy na to? @Paprikadobi @thes01 @vitkolos

**Comment by michaeldojcar** [comment]
Nastaveno a zaplaceno. @Paprikadobi Nastavil jsem ti oprávnění. Teď už jen přehodit appku od @jridky :-)

**Comment by michaeldojcar** [comment]
Čeká se na GPlay reakci.

**Comment by michaeldojcar** [comment]
Je to tam. ProScholy by Glow Space.

**Comment by vitkolos** [comment]
Hezky pěkně 👍 ❤️
