### ISSUE TITLE
Swipe animace

### ISSUE THREAD

**Issue by michaeldojcar** [proscholy/proscholy-phone#14]
Jak moc by bylo těžké, aby se swipe animoval, podle toho, jak swipuju? Že bych reálně přejížděl mezi dvěma písněmi?
Aktuálně je to tak, že swipnu a píseň instantně "přeblikne", což není úplně UX parádní, ale chápu, že to asi nebude jen tak.

Díky za info @Paprikadobi

**Comment by Paprikadobi** [comment]
Dobrý nápad, našel jsem, že na to přímo existuje widget PageView a docela to zjednodušilo logiku. Taky se tím opraví chyba, když se při změně velikosti písma přehodila aktivní píseň. 

Aktuálně to rozbilo projekční mód a při otevření písně nefunguje správně detekce automatického skrolování.

**Comment by michaeldojcar** [comment]
Dívám se, že ten příslušný commit je očíslovaný #17, asi by to mělo být #14 - podle tohoto issue.

**Comment by Paprikadobi** [comment]
jo, všiml jsem si toho, akorát když jsem to přejmenoval, tak to nezmizlo z té #17.

**Comment by michaeldojcar** [comment]
Funguje krásně!

**Comment by michaeldojcar** [comment]
Teď jsem si všiml, že pokud otevřu jediný výsledek vyhledávání, tak to swipuje mezi tou samou písní furt dokola.

**Comment by Paprikadobi** [comment]
Říkal jsem si, že něco takového nastane :D

**Comment by michaeldojcar** [comment]
Jojo, super.
