### ISSUE TITLE
UX vyladění menu

### ISSUE THREAD

**Issue by michaeldojcar** [proscholy/proscholy-phone#15]
Situace: U zpěvníku jsem zanořený na několikrát: Zpěvníky → Hosana → Píseň. Teď kliknu na navigační tlačítko Zpěvníky a dostanu se na výpis Hosany, což se zdá nepraktické, podvědomě očekávám, že spadnu přímo na zpěvníky.

Nevím, zda by chování těch navigačních tlačítek v dolním menu nešlo nějak vytunit, aby to bylo očekávatelné.
@vitkolos

**Comment by vitkolos** [comment]
Chtěl jsem si to ozkoušet, ale teď se mi už asi minutu točí načítací kolečko a píše mi to, že probíhá příprava písní. 😕 
Dobrý, tak už to najelo. Nevím, jak to myslíš – já jsem se proklikal na píseň a spodní lišta mi zmizela, žádné tlačítko Zpěvníky tam nemám. Ale jako stoprocentně v pořádku to taky není – na stránce zpěvníku mi totiž chybí ta spodní lišta. Spodní navigační lišta by totiž měla být asi úplně všude kromě zobrazení písně.

A očekávané chování je takové jako u Instagramu – příklad: jsem na stránce Zpěvníky, rozkliknu Koinonii, kliknu na lupu dole na liště (dostanu se na stránku Vyhledávání), kliknu na Zpěvníky dole na liště a hodí mě to opět do Koinonie, pak kliknu znova na Zpěvníky a hodí mě to na seznam všech zpěvníků.

Poznámka: Pokud se bavíme o nějaké dev verzi aplikace, tak se omlouvám, protože ji nemám nainstalovanou a asi nevím, jak na to.

Ještě dodám – jste dobří, ta aplikace se od poslední doby, kdy jsem ji nějak detailněji projížděl, fakt dost změnila (k lepšímu). 💪 

A rovnou reportuju pár nedostatků, na které jsem narazil:
1. Když se prokliknu ze zobrazení zpěvníku na zobrazení písně, tak mi na Androidu zůstane barevný status bar, ale ta horní aplikační lišta se obarví na bílo, takže by i ten status bar měl být asi bílý.
2. Pod barevnou horní lištou u zpěvníků vidím při rolování bílé odsazení – to by tam být nemělo, ten stín, který ta lišta vrhá, by měl padat přímo na seznam písní.
3. Když kliknu na lupu vpravo nahoře, tak by se mi měl automaticky hodit focus do toho vyhledávacího pole.

**Comment by michaeldojcar** [comment]
K tomu dolnímu menu, já ho mám úplně všude (včetně zobrazení písně). :D Mám pre-release na iOS (ale ta app by se měla chovat stejně). A teď se dívám, že když jsem zanořenej a kliknu na tu samou položku (ve které právě jsem) v dolním menu, tak už se neděje nic.

Co se týče testování, @Paprikadobi může poslat aktuální APK. Já mám na iOS takový cool oficiální testovací program, kde se mi nahrává nejnovější beta. 📦 

K těm tvým 3 reportům, první jsem založil zvlášť. #16 Zkusíš ty zbylé dva taky prosím hodit do solo issue? :-)

**Comment by Paprikadobi** [comment]
na iOS by to už mělo fungovat správně u androidu ještě budu muset vymyslet jak to udělat

**Comment by michaeldojcar** [comment]
Paráda, ty GH issues se mi líbí! Hlavně, jak jdou zmínit v commitu. Jira se může jít vycpat. :D

**Comment by vitkolos** [comment]
Omlouvám se, že jsem nezvládl založit ty issues, až teď jsem se dostal k počítači. 😅
