### ISSUE TITLE
Nová píseň se nepropsala do aplikace

### ISSUE THREAD

**Issue by michaeldojcar** [proscholy/proscholy-phone#26]
https://zpevnik.proscholy.cz/pisen/3210/pisnicka-k-jidlu

@bara-kucharikova ji včera založila, ale do appky se mi nepropsala (po manuálním refreshi ani po restartu app).

**Comment by michaeldojcar** [comment]
Neotevře se ani když zadám její číslo.

**Comment by Paprikadobi** [comment]
Pokud písnička nemá text, tak se nezobrazuje. Vidím ale, že má noty, tak upravím podmínku, že stačí i ty.

**Comment by michaeldojcar** [comment]
Jo tak, to dává smysl. :)

**Comment by michaeldojcar** [comment]
Otestováno, vypadá to dobře.
