### ISSUE TITLE
Label v ChordPro zápisu reaguje na dvojkřížek

### ISSUE THREAD

**Issue by michaeldojcar** [proscholy/proscholy-phone#32]
Pokud je uvnitř labelu na stejném řádku další # dvojkřížek
aplikace to zalomí, ale v praxi to bude zmínka o nějakém akordu uvnitř komentáře.

Hezky se to projevilo u 2817:
Web:
<img width="274" alt="Snímek obrazovky 2021-11-18 v 22 30 19" src="https://user-images.githubusercontent.com/1665018/142499846-cd46adc2-2d2b-4793-b6ec-22b290ecfdad.png">

App:
<img width="274" alt="Snímek obrazovky 2021-11-18 v 22 30 19" src="https://user-images.githubusercontent.com/1665018/142500082-b0154c83-8762-4d25-acae-a670768dc43e.jpeg">

**Comment by Paprikadobi** [comment]
Pořád čekám na chybu, kterou nedokážu opravit pomocí toho dlouhého regexu, co tam mám na parsování abych to konečně předělal nějak lépe :D

**Comment by michaeldojcar** [comment]
Haha, už to vidím. :D

**Comment by michaeldojcar** [comment]
Vypadá to dobře, díky!
