### ISSUE TITLE
Při scrollování se často focusne výsledek vyhledávání

### ISSUE THREAD

**Issue by michaeldojcar** [proscholy/proscholy-phone#35]
Tady úplně nevím, jak konkrétně z toho ven, ale stává se, že když jdu scrollovat např. výsledky vyhledávání, místo aby mi to hezky scrollnulo, promáčkne se výsledek vyhledávání, "o který" jsem začal scrollovat.

Děje se to docela často a byť to působí jako bezvýznamná drobnost, je to hrozně otravné a snižuje to celkový pocit z appky, takže kdyby se s tím povedlo něco udělat, dost by to appku zvedlo.

**Comment by Paprikadobi** [comment]
Asi nechápu co přesně myslíš. Jakože když scrolluješ, tak se focusuje to vyhledávací pole?

**Comment by michaeldojcar** [comment]
Nene, když chci scrollovat mezi výsledky, často se focusne řádek s jednou z písniček a blokne se scroll.

**Comment by Paprikadobi** [comment]
A to se děje jen na androidu nebo i iOS? Na iOS vidím, že když začnu scroll, tak se ten řádek na okamžik zvýrazní, ale nijak se to neblokne. Kdyžtak to asi prosím natoč.

**Comment by Paprikadobi** [comment]
Tak už asi vím co myslíš, mělo by to být opravené.

**Comment by michaeldojcar** [comment]
Otestováno, je to lepší. Díky.
